# importing the libraries

In [19]:
pip install xgboost

Requirement already satisfied: xgboost in c:\users\charles\anaconda3\lib\site-packages (3.0.0)
Requirement already satisfied: numpy in c:\users\charles\anaconda3\lib\site-packages (from xgboost) (1.26.4)
Requirement already satisfied: scipy in c:\users\charles\anaconda3\lib\site-packages (from xgboost) (1.13.1)
Note: you may need to restart the kernel to use updated packages.

In [23]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns 
import sklearn.datasets
import xgboost as xg

In [25]:
from sklearn.model_selection import train_test_split
from sklearn import metrics 
from xgboost import XGBRegressor

### Importing the Boston Houuse prices  dataset

In [46]:
df=pd.read_csv(r"C:\Users\Charles\Downloads\BOSTON DATASET\BostonHousing.csv")

In [48]:
df.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [50]:
df.columns

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')

In [56]:
df.rename(columns={'crim':'crime rate',
                  'zn':'zoned',
                  'indus':'indus',
                  'chas':'chas',
                  'nox':'Nitric oxide conc',
                  'rm':'number of rooms', 
                    'medv':'price'},inplace=True)

In [58]:
df.columns

Index(['crime rate', 'zoned', 'indus', 'chas', 'Nitric oxide conc',
       'number of rooms', 'age', 'dis', 'rad', 'tax', 'ptratio', 'b', 'lstat',
       'price'],
      dtype='object')

In [60]:
df.shape

(506, 14)

In [62]:
df.isnull().sum()

crime rate           0
zoned                0
indus                0
chas                 0
Nitric oxide conc    0
number of rooms      5
age                  0
dis                  0
rad                  0
tax                  0
ptratio              0
b                    0
lstat                0
price                0
dtype: int64

In [70]:
df.dropna(inplace=True)

In [74]:
df.isnull().sum()

crime rate           0
zoned                0
indus                0
chas                 0
Nitric oxide conc    0
number of rooms      0
age                  0
dis                  0
rad                  0
tax                  0
ptratio              0
b                    0
lstat                0
price                0
dtype: int64

In [76]:
df.describe()

,crime rate,zoned,indus,chas,Nitric oxide conc,number of rooms,age,dis,rad,tax,ptratio,b,lstat,price
count,501.000000,501.000000,501.000000,501.000000,501.000000,501.000000,501.000000,501.000000,501.000000,501.000000,501.000000,501.000000,501.000000,501.000000
mean,3.647414,11.402196,11.160619,0.069860,0.555151,6.284341,68.513373,3.786423,9.596806,409.143713,18.453493,356.298523,12.643752,22.561277
std,8.637688,23.414214,6.857123,0.255166,0.116186,0.705587,28.212221,2.103327,8.735509,169.021216,2.166327,91.672055,7.162746,9.232435
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.081990,0.000000,5.190000,0.000000,0.449000,5.884000,45.000000,2.088200,4.000000,279.000000,17.400000,375.210000,6.920000,17.000000
50%,0.261690,0.000000,9.690000,0.000000,0.538000,6.208000,77.700000,3.182700,5.000000,330.000000,19.000000,391.340000,11.380000,21.200000
75%,3.693110,12.500000,18.100000,0.000000,0.624000,6.625000,94.000000,5.118000,24.000000,666.000000,20.200000,396.230000,16.940000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

### Understanding the data

In [ ]:
# coreration btwn diffrent column in the dataset